package ru.churkin.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-03-01T11:18:28.265+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://endpoint.churkin.ru/", name = "ProjectEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/ProjectEndpoint/updateProjectRequest", output = "http://endpoint.churkin.ru/ProjectEndpoint/updateProjectResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/ProjectEndpoint/updateProject/Fault/Exception")})
    @RequestWrapper(localName = "updateProject", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.UpdateProject")
    @ResponseWrapper(localName = "updateProjectResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.UpdateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updateProject(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(name = "project", targetNamespace = "")
        ru.churkin.endpoint.Project project
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/ProjectEndpoint/deleteProjectRequest", output = "http://endpoint.churkin.ru/ProjectEndpoint/deleteProjectResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/ProjectEndpoint/deleteProject/Fault/Exception")})
    @RequestWrapper(localName = "deleteProject", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.DeleteProject")
    @ResponseWrapper(localName = "deleteProjectResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.DeleteProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean deleteProject(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/ProjectEndpoint/createProjectRequest", output = "http://endpoint.churkin.ru/ProjectEndpoint/createProjectResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/ProjectEndpoint/createProject/Fault/Exception")})
    @RequestWrapper(localName = "createProject", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.CreateProject")
    @ResponseWrapper(localName = "createProjectResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.CreateProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean createProject(
        @WebParam(name = "project", targetNamespace = "")
        ru.churkin.endpoint.Project project
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/ProjectEndpoint/findProjectByNameRequest", output = "http://endpoint.churkin.ru/ProjectEndpoint/findProjectByNameResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/ProjectEndpoint/findProjectByName/Fault/Exception")})
    @RequestWrapper(localName = "findProjectByName", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.FindProjectByName")
    @ResponseWrapper(localName = "findProjectByNameResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.FindProjectByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.churkin.endpoint.Project findProjectByName(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/ProjectEndpoint/getAllProjectsRequest", output = "http://endpoint.churkin.ru/ProjectEndpoint/getAllProjectsResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/ProjectEndpoint/getAllProjects/Fault/Exception")})
    @RequestWrapper(localName = "getAllProjects", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.GetAllProjects")
    @ResponseWrapper(localName = "getAllProjectsResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.GetAllProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ru.churkin.endpoint.Project> getAllProjects() throws Exception_Exception;
}
