package ru.churkin.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2019-02-28T18:45:58.582+03:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://endpoint.churkin.ru/", name = "UserEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserEndpoint {

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/createNewUserRequest", output = "http://endpoint.churkin.ru/UserEndpoint/createNewUserResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/UserEndpoint/createNewUser/Fault/Exception")})
    @RequestWrapper(localName = "createNewUser", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.CreateNewUser")
    @ResponseWrapper(localName = "createNewUserResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.CreateNewUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean createNewUser(
        @WebParam(name = "user", targetNamespace = "")
        ru.churkin.endpoint.User user
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/isExistRequest", output = "http://endpoint.churkin.ru/UserEndpoint/isExistResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/UserEndpoint/isExist/Fault/Exception")})
    @RequestWrapper(localName = "isExist", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.IsExist")
    @ResponseWrapper(localName = "isExistResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.IsExistResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean isExist(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/findUserByIdRequest", output = "http://endpoint.churkin.ru/UserEndpoint/findUserByIdResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/UserEndpoint/findUserById/Fault/Exception")})
    @RequestWrapper(localName = "findUserById", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.FindUserById")
    @ResponseWrapper(localName = "findUserByIdResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.FindUserByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.churkin.endpoint.User findUserById(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/getUserByNameRequest", output = "http://endpoint.churkin.ru/UserEndpoint/getUserByNameResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/UserEndpoint/getUserByName/Fault/Exception")})
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.GetUserByName")
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.GetUserByNameResponse")
    public void getUserByName(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/getCurrentUserRequest", output = "http://endpoint.churkin.ru/UserEndpoint/getCurrentUserResponse")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.GetCurrentUser")
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.GetCurrentUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ru.churkin.endpoint.User getCurrentUser();

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/validateUserRequest", output = "http://endpoint.churkin.ru/UserEndpoint/validateUserResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/UserEndpoint/validateUser/Fault/Exception")})
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.ValidateUser")
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.ValidateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean validateUser(
        @WebParam(name = "user", targetNamespace = "")
        ru.churkin.endpoint.User user
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://endpoint.churkin.ru/UserEndpoint/setCurrentUserRequest", output = "http://endpoint.churkin.ru/UserEndpoint/setCurrentUserResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://endpoint.churkin.ru/UserEndpoint/setCurrentUser/Fault/Exception")})
    @RequestWrapper(localName = "setCurrentUser", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.SetCurrentUser")
    @ResponseWrapper(localName = "setCurrentUserResponse", targetNamespace = "http://endpoint.churkin.ru/", className = "ru.churkin.endpoint.SetCurrentUserResponse")
    public void setCurrentUser(
        @WebParam(name = "arg0", targetNamespace = "")
        ru.churkin.endpoint.User arg0
    ) throws Exception_Exception;
}
